# Build settings
markdown: kramdown
highlighter: rouge

# Site settings
title: "Charlie Chang"
description: > # this means to ignore newlines until "email:"
    murmuring....

email: icharlie.osu@gmail.com
#blog logo
logo: "/assets/images/cc_logo.jpg"
# blog cover
#cover: "/assets/images/cover.jpg"

name: 'Charlie Chang'
author: 'Charlie Chang'
author_image: "/assets/images/author.jpg"

paginate:	10

# Plugins
gems:
  - jekyll-paginate
  - jekyll-gist

url: "http://www.charliechang.tw" # the base hostname & protocol for your site
baseurl: ""

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/cr0rc
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: //www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/icharlie
    desc:	Check my work on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
